### ISSUE TITLE
Remove 0/1 from default list

### ISSUE THREAD

**Issue by kiryph** [bootleq/vim-cycle#12]
Why is 0/1 in the default list?

For people who overwrite ctrl-a/x this interfers with incrementing of numbers.

I do also not think that toggling 0/1 is a reason to install this plugin.

**Comment by bootleq** [comment]
The intention of `0`/`1` is for some "switching" thing like `on`/`off`.

I think the "default" here is more like an example for user, since the recommended way to config groups is `g:cycle_default_groups` which will hide the `0`/`1`, `+`/`-` things anyway.

Since it doesn't affect most users and provides a basic example idea, I guess keep it would be fine.

**Comment by kiryph** [comment]
> The intention of 0/1 is for some "switching" thing like on/off.

I was assuming this. But I am still not convinced 😃. There are other examples for boolean values in the "default" group which make this already clear: true/false, on/off, yes/no; no need for 0/1. If someone wants this, he/she should add this.

> I think the "default" here is more like an example for user, since the recommended way to config groups is g:cycle_default_groups which will hide the 0/1, +/- things anyway.

Then I would remove the definition of `g:cycle_default_group` from `plugin/cycle.vim` and would follow the route of the snippet plugins UltiSnips and neosnippet which do not contain any snippets out of the box.

> Since it doesn't affect most users and provides a basic example idea, I guess keep it would be fine.

I would argue the provided configuration examples should give examples which are not possible with default vim. Toggling 0 and 1 is possible with default vim and there is not much improvement by vim-cycle. I think advocating to use default vim where possible should be worthwhile (https://www.vi-improved.org/recommendations/).

IMHO, the idea of extending ctrl-a/x as done in swapit.vim, vim-speeddating, and vim-CtrlXA is great. I would suggest that the README.md and doc/cycle.vim mention that this is also possible with this plugin.

Another idea:
What about having a wiki page where user can publish their own cycle_groups for the inspiration of other users/newbies?

**Comment by bootleq** [comment]
Personally I like the idea to remove all defaults in `plugin/cycle.vim`, since advanced users always have their own group setting.

For users usually install plugins without customization,
I am going to remove `0/1`, `+/-` and `>/<` from defaults, to make it minimal and avoid surprising users.

About the "advocating default vim" idea, yes I follow the concept,
but I don't think default Vim has a toggle operation, it can **change** `0` to `1`, but it is the same as change `true` to `false`, it is slightly different to toggle or cycle.

For other suggestions, welcome to open new issues, that will be easier to follow, thank you very much.

**Comment by bootleq** [comment]
`0` / `1` has been removed at version `0.4.0`.
